openapi: 3.0.0
info:
  contact:
    email: support@openweb3.io
    name: API Support
  description: This is a pay service api server.
  title: Pay OpenAPI Documentations
  version: "1.0"
servers:
- url: /
paths:
  /api/v1/apps/{appId}/currencies/crypto:
    get:
      description: List available cryptocurrencies
      operationId: v1.currencies.listCrypto
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CryptoCurrency'
                type: array
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: List available cryptocurrencies
      tags:
      - currency
  /api/v1/apps/{appId}/currencies/fiat:
    get:
      description: List available fiat currencies
      operationId: v1.currencies.listFlat
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/FiatCurrency'
                type: array
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: List available fiat currencies
      tags:
      - currency
  /api/v1/apps/{appId}/currencies/rate:
    get:
      description: Get exchange rate
      operationId: v1.currencies.retrieveRate
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: From currency
        explode: true
        in: query
        name: from
        required: true
        schema:
          type: string
        style: form
      - description: To currency
        explode: true
        in: query
        name: to
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Rate'
                type: array
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: Get exchange rate
      tags:
      - currency
  /api/v1/apps/{appId}/endpoints:
    get:
      description: List webhook endpoints
      operationId: v1.endpoints.list
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Cursor
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
        style: form
      - description: Limit
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: Ordering
        explode: true
        in: query
        name: ordering
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CursorPage-Webhook'
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: List webhook endpoints
      tags:
      - webhook
    post:
      description: Create a webhook endpoint
      operationId: v1.endpoints.create
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWebhook'
        description: Request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: Create a webhook endpoint
      tags:
      - webhook
  /api/v1/apps/{appId}/endpoints/{endpointId}:
    delete:
      description: Delete a webhook endpoint
      operationId: v1.endpoints.delete
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Endpoint ID
        explode: false
        in: path
        name: endpointId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: Delete a webhook endpoint
      tags:
      - webhook
    get:
      description: Retrieve a webhook endpoint
      operationId: v1.endpoints.retrieve
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Endpoint ID
        explode: false
        in: path
        name: endpointId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: Retrieve a webhook endpoint
      tags:
      - webhook
    patch:
      description: Update a webhook endpoint
      operationId: v1.endpoints.update
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Endpoint ID
        explode: false
        in: path
        name: endpointId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWebhook'
        description: Request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: Update a webhook endpoint
      tags:
      - webhook
  /api/v1/apps/{appId}/invoices:
    get:
      description: List invoices
      operationId: v1.invoices.list
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Cursor
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
        style: form
      - description: Limit
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: Ordering
        explode: true
        in: query
        name: ordering
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page-Invoice'
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: List invoices
      tags:
      - invoice
    post:
      description: Create an invoice
      operationId: v1.invoices.create
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInvoiceRequest'
        description: Request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: Create an invoice
      tags:
      - invoice
  /api/v1/apps/{appId}/invoices/{invoiceId}:
    get:
      description: Retrieve an invoice
      operationId: v1.invoices.retrieve
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Invoice ID / UID
        explode: false
        in: path
        name: invoiceId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
          description: OK
      security:
      - ApiKeyAuth: []
      - SignatureAuth: []
      summary: Retrieve an invoice
      tags:
      - invoice
components:
  schemas:
    CreateInvoiceRequest:
      example:
        note: note
        uid: uid
        amount: amount
        metadata:
          key: ""
        extra:
          key: ""
        channel: channel
        currency: currency
        expiration: 0
        userId: userId
      properties:
        amount:
          description: Amount (Integer)
          type: string
        channel:
          description: Channel
          type: string
        currency:
          description: Currency
          type: string
        expiration:
          description: Expiration
          type: integer
        extra:
          additionalProperties: {}
          description: Extra
          type: object
        metadata:
          additionalProperties: {}
          description: Metadata
          type: object
        note:
          description: Note
          type: string
        uid:
          description: Unique ID
          type: string
        userId:
          description: User ID
          type: string
      required:
      - amount
      - channel
      - currency
      type: object
    CreateWebhook:
      example:
        headers:
          key: headers
        uid: uid
        metadata:
          key: ""
        description: description
        disabled: true
        eventTypes:
        - eventTypes
        - eventTypes
        url: url
      properties:
        description:
          description: The description of the webhook
          type: string
        disabled:
          description: The disabled of the webhook
          type: boolean
        eventTypes:
          description: The event types of the webhook
          items:
            type: string
          type: array
        headers:
          additionalProperties:
            type: string
          description: The headers of the webhook
          type: object
        metadata:
          additionalProperties: {}
          description: The metadata of the webhook
          type: object
        uid:
          description: The uid of the webhook
          type: string
        url:
          description: The url of the webhook
          type: string
      type: object
    CryptoCurrency:
      example:
        minWithdrawAmount: minWithdrawAmount
        maxWithdrawAmount: maxWithdrawAmount
        code: code
        decimals: 0
        precision: 6
        minDepositAmount: minDepositAmount
        name: name
        networks:
        - code: code
          canTransfer: true
          canWithdraw: true
          name: name
          canDeposit: true
          network: network
        - code: code
          canTransfer: true
          canWithdraw: true
          name: name
          canDeposit: true
          network: network
      properties:
        code:
          description: Currency code
          type: string
        decimals:
          description: Decimals
          type: integer
        maxWithdrawAmount:
          description: Max Withdraw Amount (Integer)
          type: string
        minDepositAmount:
          description: Min Deposit Amount (Integer)
          type: string
        minWithdrawAmount:
          description: Min Withdraw Amount (Integer)
          type: string
        name:
          description: Currency name
          type: string
        networks:
          description: Networks
          items:
            $ref: '#/components/schemas/CryptoCurrencyNetwork'
          type: array
        precision:
          description: Precision
          type: integer
      type: object
    CryptoCurrencyNetwork:
      example:
        code: code
        canTransfer: true
        canWithdraw: true
        name: name
        canDeposit: true
        network: network
      properties:
        canDeposit:
          description: Can Deposit
          type: boolean
        canTransfer:
          description: Can Transfer
          type: boolean
        canWithdraw:
          description: Can Withdraw
          type: boolean
        code:
          description: Network code
          type: string
        name:
          description: Network display name
          type: string
        network:
          description: Network name
          type: string
      type: object
    CursorPage-Webhook:
      example:
        prev_cursor: prev_cursor
        next_cursor: next_cursor
        items:
        - filter: filter
          createdAt: createdAt
          headers:
            key: headers
          uid: uid
          metadata:
            key: ""
          description: description
          disabled: true
          id: id
          eventTypes:
          - eventTypes
          - eventTypes
          url: url
        - filter: filter
          createdAt: createdAt
          headers:
            key: headers
          uid: uid
          metadata:
            key: ""
          description: description
          disabled: true
          id: id
          eventTypes:
          - eventTypes
          - eventTypes
          url: url
      properties:
        items:
          items:
            $ref: '#/components/schemas/Webhook'
          type: array
        next_cursor:
          type: string
        prev_cursor:
          type: string
      type: object
    FiatCurrency:
      example:
        code: code
        name: name
      properties:
        code:
          description: Currency Code
          type: string
        name:
          description: Currency Name
          type: string
      type: object
    Invoice:
      example:
        note: note
        amount: amount
        metadata:
          key: ""
        credentials:
          key: ""
        channel: channel
        userId: userId
        createdAt: createdAt
        expiredAt: expiredAt
        uid: uid
        failedAt: failedAt
        extra:
          key: ""
        base_amount: base_amount
        paidAt: paidAt
        currency: currency
        expiration: 0
        id: id
        failedReason: failedReason
      properties:
        amount:
          description: Amount (Integer)
          type: string
        base_amount:
          description: Base Currency Amount
          type: string
        channel:
          type: string
        createdAt:
          type: string
        credentials:
          additionalProperties: {}
          type: object
        currency:
          type: string
        expiration:
          type: integer
        expiredAt:
          type: string
        extra:
          additionalProperties: {}
          type: object
        failedAt:
          type: string
        failedReason:
          type: string
        id:
          type: string
        metadata:
          additionalProperties: {}
          type: object
        note:
          type: string
        paidAt:
          type: string
        status:
          $ref: '#/components/schemas/InvoiceStatus'
        uid:
          type: string
        userId:
          type: string
      type: object
    InvoiceStatus:
      enum:
      - FAILED
      - PENDING
      - EXPIRED
      - PAID
      - COMPLETED
      type: string
      x-enum-varnames:
      - InvoiceStatusFailed
      - InvoiceStatusPending
      - InvoiceStatusExpired
      - InvoiceStatusPaid
      - InvoiceStatusCompleted
    Page-Invoice:
      example:
        prev_cursor: prev_cursor
        next_cursor: next_cursor
        total: 6
        data:
        - note: note
          amount: amount
          metadata:
            key: ""
          credentials:
            key: ""
          channel: channel
          userId: userId
          createdAt: createdAt
          expiredAt: expiredAt
          uid: uid
          failedAt: failedAt
          extra:
            key: ""
          base_amount: base_amount
          paidAt: paidAt
          currency: currency
          expiration: 0
          id: id
          failedReason: failedReason
        - note: note
          amount: amount
          metadata:
            key: ""
          credentials:
            key: ""
          channel: channel
          userId: userId
          createdAt: createdAt
          expiredAt: expiredAt
          uid: uid
          failedAt: failedAt
          extra:
            key: ""
          base_amount: base_amount
          paidAt: paidAt
          currency: currency
          expiration: 0
          id: id
          failedReason: failedReason
        hasPrev: true
        hasNext: true
      properties:
        data:
          items:
            $ref: '#/components/schemas/Invoice'
          type: array
        hasNext:
          type: boolean
        hasPrev:
          type: boolean
        next_cursor:
          type: string
        prev_cursor:
          type: string
        total:
          type: integer
      type: object
    Rate:
      example:
        rate: rate
        toCurrency: toCurrency
        fromCurrency: fromCurrency
      properties:
        fromCurrency:
          description: From currency code
          type: string
        rate:
          description: Exchange Rate
          type: string
        toCurrency:
          description: To currency code
          type: string
      type: object
    UpdateWebhook:
      example:
        headers:
          key: headers
        uid: uid
        metadata:
          key: ""
        description: description
        disabled: true
        eventTypes:
        - eventTypes
        - eventTypes
        url: url
      properties:
        description:
          type: string
        disabled:
          type: boolean
        eventTypes:
          items:
            type: string
          type: array
        headers:
          additionalProperties:
            type: string
          type: object
        metadata:
          additionalProperties: {}
          type: object
        uid:
          type: string
        url:
          type: string
      type: object
    Webhook:
      example:
        filter: filter
        createdAt: createdAt
        headers:
          key: headers
        uid: uid
        metadata:
          key: ""
        description: description
        disabled: true
        id: id
        eventTypes:
        - eventTypes
        - eventTypes
        url: url
      properties:
        createdAt:
          type: string
        description:
          type: string
        disabled:
          type: boolean
        eventTypes:
          items:
            type: string
          type: array
        filter:
          type: string
        headers:
          additionalProperties:
            type: string
          type: object
        id:
          type: string
        metadata:
          additionalProperties: {}
          type: object
        uid:
          type: string
        url:
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: x-api-key
      type: apiKey
    SignatureAuth:
      in: header
      name: Authorization
      type: apiKey
