openapi: 3.0.2
info:
  contact:
    email: support@openweb3.io
    name: API Support
  description: This is a pay service api server.
  title: Pay OpenAPI Documentations
  version: "1.0"
externalDocs: {}
servers:
- description: Pay API Server
  url: https://api.pay.openweb3.io
paths:
  /api/v1/apps/{appId}/currencies/crypto:
    get:
      description: List available cryptocurrencies
      operationId: v1.currencies.listCrypto
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CryptoCurrency'
                type: array
          description: OK
      security:
      - ApiKeyAuth: []
      summary: List available cryptocurrencies
      tags:
      - currency
      x-accepts: application/json
  /api/v1/apps/{appId}/currencies/fiat:
    get:
      description: List available fiat currencies
      operationId: v1.currencies.listFlat
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/FiatCurrency'
                type: array
          description: OK
      security:
      - ApiKeyAuth: []
      summary: List available fiat currencies
      tags:
      - currency
      x-accepts: application/json
  /api/v1/apps/{appId}/currencies/rate:
    get:
      description: Get exchange rate
      operationId: v1.currencies.retrieveRate
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: From currency
        explode: true
        in: query
        name: fromCurrency
        required: true
        schema:
          type: string
        style: form
      - description: To currency
        explode: true
        in: query
        name: toCurrency
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Rate'
                type: array
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get exchange rate
      tags:
      - currency
      x-accepts: application/json
  /api/v1/apps/{appId}/endpoints:
    get:
      description: List webhook endpoints
      operationId: v1.endpoints.list
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: limit
        required: true
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CursorPage-Webhook'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: List webhook endpoints
      tags:
      - webhook
      x-accepts: application/json
    post:
      description: Create a webhook endpoint
      operationId: v1.endpoints.create
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWebhook'
        description: Request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Create a webhook endpoint
      tags:
      - webhook
      x-contentType: application/json
      x-accepts: application/json
  /api/v1/apps/{appId}/endpoints/{endpointId}:
    delete:
      description: Delete a webhook endpoint
      operationId: v1.endpoints.delete
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Endpoint ID
        explode: false
        in: path
        name: endpointId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Delete a webhook endpoint
      tags:
      - webhook
      x-accepts: application/json
    get:
      description: Retrieve a webhook endpoint
      operationId: v1.endpoints.retrieve
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Endpoint ID
        explode: false
        in: path
        name: endpointId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Retrieve a webhook endpoint
      tags:
      - webhook
      x-accepts: application/json
    patch:
      description: Update a webhook endpoint
      operationId: v1.endpoints.update
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Endpoint ID
        explode: false
        in: path
        name: endpointId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWebhook'
        description: Request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Update a webhook endpoint
      tags:
      - webhook
      x-contentType: application/json
      x-accepts: application/json
  /api/v1/apps/{appId}/invoices:
    get:
      description: List invoices
      operationId: v1.invoices.list
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: channel
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: userId
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page-Invoice'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: List invoices
      tags:
      - invoice
      x-accepts: application/json
    post:
      description: Create an invoice
      operationId: v1.invoices.create
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInvoiceRequest'
        description: Request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Create an invoice
      tags:
      - invoice
      x-contentType: application/json
      x-accepts: application/json
  /api/v1/apps/{appId}/invoices/{invoiceId}:
    get:
      description: Retrieve an invoice
      operationId: v1.invoices.retrieve
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Invoice ID / UID
        explode: false
        in: path
        name: invoiceId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Retrieve an invoice
      tags:
      - invoice
      x-accepts: application/json
  /api/v1/apps/{appId}/payouts:
    get:
      description: List payouts
      operationId: v1.payouts.list
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Cursor
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
        style: form
      - description: Limit
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CursorPage-Payout'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: List payouts
      tags:
      - payout
      x-accepts: application/json
    post:
      description: Payout to address
      operationId: v1.payouts.create
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePayout'
        description: Request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payout'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Payout to address
      tags:
      - payout
      x-contentType: application/json
      x-accepts: application/json
  /api/v1/apps/{appId}/payouts/{payoutId}:
    get:
      description: Retrieve a payout
      operationId: v1.payouts.retrieve
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Payout ID
        explode: false
        in: path
        name: payoutId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payout'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Retrieve a payout
      tags:
      - payout
      x-accepts: application/json
  /api/v1/apps/{appId}/refunds:
    get:
      description: List refunds
      operationId: v1.refunds.list
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Cursor
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
        style: form
      - description: Limit
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CursorPage-Refund'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: List refunds
      tags:
      - refund
      x-accepts: application/json
    post:
      description: Refund invoice payment
      operationId: v1.refunds.create
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRefund'
        description: Request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Refund'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Refund invoice payment
      tags:
      - refund
      x-contentType: application/json
      x-accepts: application/json
  /api/v1/apps/{appId}/refunds/{refundId}:
    get:
      description: Retrieve a refund
      operationId: v1.refunds.retrieve
      parameters:
      - description: App ID
        explode: false
        in: path
        name: appId
        required: true
        schema:
          type: string
        style: simple
      - description: Refund ID
        explode: false
        in: path
        name: refundId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Refund'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Retrieve a refund
      tags:
      - refund
      x-accepts: application/json
components:
  schemas:
    CreateInvoiceRequest:
      example:
        note: note
        uid: uid
        amount: amount
        metadata:
          key: ""
        provider: provider
        extra:
          key: ""
        channel: channel
        currency: currency
        expiration: 0
        userId: userId
      properties:
        amount:
          description: Amount (Integer)
          type: string
        channel:
          description: Channel
          type: string
        currency:
          description: Currency
          type: string
        expiration:
          description: Expiration
          type: integer
        extra:
          additionalProperties: {}
          description: Extra
          type: object
        metadata:
          additionalProperties: {}
          description: Metadata
          type: object
        note:
          description: Note
          type: string
        provider:
          description: Provider
          type: string
        uid:
          description: Unique ID
          type: string
        userId:
          description: User ID
          type: string
      required:
      - amount
      - channel
      - currency
      - extra
      - metadata
      - provider
      type: object
    CreatePayout:
      example:
        note: note
        amount: amount
        currency: currency
        toAddress: toAddress
        userId: userId
        network: network
      properties:
        amount:
          description: Amount (Integer)
          type: string
        currency:
          description: Currency Code
          type: string
        network:
          description: Currency Network
          type: string
        note:
          description: Payout notes
          type: string
        toAddress:
          description: To Address
          type: string
        userId:
          description: User ID
          type: string
      type: object
    CreateRefund:
      example:
        note: note
        amount: 0.8008281904610115
        invoiceId: invoiceId
        toAddress: toAddress
      properties:
        amount:
          description: Refund amount (Integer)
          type: number
        invoiceId:
          description: Invoice ID
          type: string
        note:
          description: Refund note
          type: string
        toAddress:
          description: To Address
          type: string
      type: object
    CreateWebhook:
      example:
        headers:
          key: headers
        uid: uid
        metadata:
          key: ""
        description: description
        disabled: true
        eventTypes:
        - eventTypes
        - eventTypes
        url: url
      properties:
        description:
          description: The description of the webhook
          type: string
        disabled:
          description: The disabled of the webhook
          type: boolean
        eventTypes:
          description: The event types of the webhook
          items:
            type: string
          type: array
          uniqueItems: false
        headers:
          additionalProperties:
            type: string
          description: The headers of the webhook
          type: object
        metadata:
          additionalProperties: {}
          description: The metadata of the webhook
          type: object
        uid:
          description: The uid of the webhook
          type: string
        url:
          description: The url of the webhook
          type: string
      required:
      - disabled
      - eventTypes
      - headers
      - metadata
      - url
      type: object
    CryptoCurrency:
      example:
        minWithdrawAmount: minWithdrawAmount
        maxWithdrawAmount: maxWithdrawAmount
        code: code
        decimals: 0
        precision: 6
        minDepositAmount: minDepositAmount
        name: name
        networks:
        - code: code
          canTransfer: true
          canWithdraw: true
          name: name
          canDeposit: true
          network: network
        - code: code
          canTransfer: true
          canWithdraw: true
          name: name
          canDeposit: true
          network: network
      properties:
        code:
          description: Currency code
          type: string
        decimals:
          description: Decimals
          type: integer
        maxWithdrawAmount:
          description: Max Withdraw Amount (Integer)
          type: string
        minDepositAmount:
          description: Min Deposit Amount (Integer)
          type: string
        minWithdrawAmount:
          description: Min Withdraw Amount (Integer)
          type: string
        name:
          description: Currency name
          type: string
        networks:
          description: Networks
          items:
            $ref: '#/components/schemas/CryptoCurrencyNetwork'
          type: array
          uniqueItems: false
        precision:
          description: Precision
          type: integer
      required:
      - code
      - decimals
      - maxWithdrawAmount
      - minDepositAmount
      - minWithdrawAmount
      - name
      - networks
      - precision
      type: object
    CryptoCurrencyNetwork:
      example:
        code: code
        canTransfer: true
        canWithdraw: true
        name: name
        canDeposit: true
        network: network
      properties:
        canDeposit:
          description: Can Deposit
          type: boolean
        canTransfer:
          description: Can Transfer
          type: boolean
        canWithdraw:
          description: Can Withdraw
          type: boolean
        code:
          description: Network code
          type: string
        name:
          description: Network display name
          type: string
        network:
          description: Network name
          type: string
      required:
      - canDeposit
      - canTransfer
      - canWithdraw
      - code
      - name
      - network
      type: object
    CursorPage-Payout:
      example:
        prev_cursor: prev_cursor
        next_cursor: next_cursor
        items:
        - note: note
          amount: amount
          completedAt: completedAt
          toAddress: toAddress
          userId: userId
          network: network
          createdAt: createdAt
          failedAt: failedAt
          currency: currency
          fromAddress: fromAddress
          id: id
          failedReason: failedReason
          status: status
          updatedAt: updatedAt
        - note: note
          amount: amount
          completedAt: completedAt
          toAddress: toAddress
          userId: userId
          network: network
          createdAt: createdAt
          failedAt: failedAt
          currency: currency
          fromAddress: fromAddress
          id: id
          failedReason: failedReason
          status: status
          updatedAt: updatedAt
      properties:
        items:
          items:
            $ref: '#/components/schemas/Payout'
          type: array
          uniqueItems: false
        next_cursor:
          type: string
        prev_cursor:
          type: string
      type: object
    CursorPage-Refund:
      example:
        prev_cursor: prev_cursor
        next_cursor: next_cursor
        items:
        - createdAt: createdAt
          note: note
          amount: 0.8008281904610115
          completedAt: completedAt
          failedAt: failedAt
          invoiceId: invoiceId
          id: id
          toAddress: toAddress
          failedReason: failedReason
          status: status
          updatedAt: updatedAt
        - createdAt: createdAt
          note: note
          amount: 0.8008281904610115
          completedAt: completedAt
          failedAt: failedAt
          invoiceId: invoiceId
          id: id
          toAddress: toAddress
          failedReason: failedReason
          status: status
          updatedAt: updatedAt
      properties:
        items:
          items:
            $ref: '#/components/schemas/Refund'
          type: array
          uniqueItems: false
        next_cursor:
          type: string
        prev_cursor:
          type: string
      type: object
    CursorPage-Webhook:
      example:
        prev_cursor: prev_cursor
        next_cursor: next_cursor
        items:
        - filter: filter
          createdAt: 2000-01-23T04:56:07.000+00:00
          headers:
            key: headers
          uid: uid
          metadata:
            key: ""
          description: description
          disabled: true
          id: id
          eventTypes:
          - eventTypes
          - eventTypes
          url: url
        - filter: filter
          createdAt: 2000-01-23T04:56:07.000+00:00
          headers:
            key: headers
          uid: uid
          metadata:
            key: ""
          description: description
          disabled: true
          id: id
          eventTypes:
          - eventTypes
          - eventTypes
          url: url
      properties:
        items:
          items:
            $ref: '#/components/schemas/Webhook'
          type: array
          uniqueItems: false
        next_cursor:
          type: string
        prev_cursor:
          type: string
      type: object
    FiatCurrency:
      example:
        code: code
        name: name
      properties:
        code:
          description: Currency Code
          type: string
        name:
          description: Currency Name
          type: string
      required:
      - code
      - name
      type: object
    Invoice:
      example:
        note: note
        amount: amount
        metadata:
          key: ""
        credentials:
          key: ""
        channel: channel
        userId: userId
        createdAt: 2000-01-23T04:56:07.000+00:00
        expiredAt: 2000-01-23T04:56:07.000+00:00
        uid: uid
        failedAt: 2000-01-23T04:56:07.000+00:00
        provider: provider
        extra:
          key: ""
        base_amount: base_amount
        paidAt: 2000-01-23T04:56:07.000+00:00
        currency: currency
        expiration: 0
        id: id
        failedReason: failedReason
        status: status
      properties:
        amount:
          description: Amount (Integer)
          type: string
        base_amount:
          description: Base Currency Amount
          type: string
        channel:
          type: string
        createdAt:
          format: date-time
          type: string
        credentials:
          additionalProperties: {}
          type: object
        currency:
          type: string
        expiration:
          type: integer
        expiredAt:
          format: date-time
          type: string
        extra:
          additionalProperties: {}
          type: object
        failedAt:
          format: date-time
          type: string
        failedReason:
          type: string
        id:
          type: string
        metadata:
          additionalProperties: {}
          type: object
        note:
          type: string
        paidAt:
          format: date-time
          type: string
        provider:
          type: string
        status:
          type: string
          x-enum-varnames:
          - InvoiceStatusFailed
          - InvoiceStatusPending
          - InvoiceStatusExpired
          - InvoiceStatusPaid
          - InvoiceStatusCompleted
        uid:
          type: string
        userId:
          type: string
      required:
      - amount
      - base_amount
      - channel
      - createdAt
      - credentials
      - currency
      - extra
      - id
      - metadata
      - note
      - provider
      - status
      type: object
    InvoiceStatus:
      type: string
      x-enum-varnames:
      - InvoiceStatusFailed
      - InvoiceStatusPending
      - InvoiceStatusExpired
      - InvoiceStatusPaid
      - InvoiceStatusCompleted
    Page-Invoice:
      example:
        prev_cursor: prev_cursor
        next_cursor: next_cursor
        total: 6
        data:
        - note: note
          amount: amount
          metadata:
            key: ""
          credentials:
            key: ""
          channel: channel
          userId: userId
          createdAt: 2000-01-23T04:56:07.000+00:00
          expiredAt: 2000-01-23T04:56:07.000+00:00
          uid: uid
          failedAt: 2000-01-23T04:56:07.000+00:00
          provider: provider
          extra:
            key: ""
          base_amount: base_amount
          paidAt: 2000-01-23T04:56:07.000+00:00
          currency: currency
          expiration: 0
          id: id
          failedReason: failedReason
          status: status
        - note: note
          amount: amount
          metadata:
            key: ""
          credentials:
            key: ""
          channel: channel
          userId: userId
          createdAt: 2000-01-23T04:56:07.000+00:00
          expiredAt: 2000-01-23T04:56:07.000+00:00
          uid: uid
          failedAt: 2000-01-23T04:56:07.000+00:00
          provider: provider
          extra:
            key: ""
          base_amount: base_amount
          paidAt: 2000-01-23T04:56:07.000+00:00
          currency: currency
          expiration: 0
          id: id
          failedReason: failedReason
          status: status
        hasPrev: true
        hasNext: true
      properties:
        data:
          items:
            $ref: '#/components/schemas/Invoice'
          type: array
        hasNext:
          type: boolean
        hasPrev:
          type: boolean
        next_cursor:
          type: string
        prev_cursor:
          type: string
        total:
          type: integer
      type: object
    Payout:
      example:
        note: note
        amount: amount
        completedAt: completedAt
        toAddress: toAddress
        userId: userId
        network: network
        createdAt: createdAt
        failedAt: failedAt
        currency: currency
        fromAddress: fromAddress
        id: id
        failedReason: failedReason
        status: status
        updatedAt: updatedAt
      properties:
        amount:
          description: Amount (Integer)
          type: string
        completedAt:
          description: Completed at
          type: string
        createdAt:
          description: Created at
          type: string
        currency:
          description: Currency Code
          type: string
        failedAt:
          description: Failed at
          type: string
        failedReason:
          description: Failed reason
          type: string
        fromAddress:
          description: From Address
          type: string
        id:
          type: string
        network:
          description: Currency Network
          type: string
        note:
          description: Payout note
          type: string
        status:
          description: Payout status
          type: string
        toAddress:
          description: To Address
          type: string
        updatedAt:
          description: Updated at
          type: string
        userId:
          description: User ID
          type: string
      type: object
    Rate:
      example:
        rate: rate
        toCurrency: toCurrency
        fromCurrency: fromCurrency
      properties:
        fromCurrency:
          description: From currency code
          type: string
        rate:
          description: Exchange Rate
          type: string
        toCurrency:
          description: To currency code
          type: string
      required:
      - fromCurrency
      - rate
      - toCurrency
      type: object
    Refund:
      example:
        createdAt: createdAt
        note: note
        amount: 0.8008281904610115
        completedAt: completedAt
        failedAt: failedAt
        invoiceId: invoiceId
        id: id
        toAddress: toAddress
        failedReason: failedReason
        status: status
        updatedAt: updatedAt
      properties:
        amount:
          description: Refund amount (Integer)
          type: number
        completedAt:
          description: Completed at
          type: string
        createdAt:
          description: Created at
          type: string
        failedAt:
          description: Failed at
          type: string
        failedReason:
          description: Failed reason
          type: string
        id:
          type: string
        invoiceId:
          description: Invoice ID
          type: string
        note:
          description: Refund note
          type: string
        status:
          description: Refund status
          type: string
        toAddress:
          description: To Address
          type: string
        updatedAt:
          description: Updated at
          type: string
      type: object
    UpdateWebhook:
      example:
        headers:
          key: headers
        uid: uid
        metadata:
          key: ""
        description: description
        disabled: true
        eventTypes:
        - eventTypes
        - eventTypes
        url: url
      properties:
        description:
          type: string
        disabled:
          type: boolean
        eventTypes:
          items:
            type: string
          type: array
          uniqueItems: false
        headers:
          additionalProperties:
            type: string
          type: object
        metadata:
          additionalProperties: {}
          type: object
        uid:
          type: string
        url:
          type: string
      required:
      - eventTypes
      - headers
      - metadata
      type: object
    Webhook:
      example:
        filter: filter
        createdAt: 2000-01-23T04:56:07.000+00:00
        headers:
          key: headers
        uid: uid
        metadata:
          key: ""
        description: description
        disabled: true
        id: id
        eventTypes:
        - eventTypes
        - eventTypes
        url: url
      properties:
        createdAt:
          format: date-time
          type: string
        description:
          type: string
        disabled:
          type: boolean
        eventTypes:
          items:
            type: string
          type: array
          uniqueItems: false
        filter:
          type: string
        headers:
          additionalProperties:
            type: string
          type: object
        id:
          type: string
        metadata:
          additionalProperties: {}
          type: object
        uid:
          type: string
        url:
          type: string
      required:
      - createdAt
      - description
      - eventTypes
      - filter
      - headers
      - id
      - metadata
      - url
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: x-api-key
      type: apiKey

